version: "3.7"
services:
    nodeapp:
      container_name: api-tutor
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "4444:3000"
      depends_on:
        - db    
        
    db:
      image: "mysql:5.7"
      environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: "tutornow"
            MYSQL_USER: user
            MYSQL_PASSWORD: user
      ports: 
        - "9000:3306"